import type { AITradeSignal, WhaleTransaction, PricePrediction } from "./types";

export const mockSignals: AITradeSignal[] = [
  {
    id: "sig-1",
    coinId: "solana",
    symbol: "SOL",
    name: "Solana",
    image: "https://assets.coingecko.com/coins/images/4128/small/solana.png",
    signalType: "STRONG_BUY",
    confidence: 87,
    currentPrice: 198.45,
    entryPrice: 195.0,
    stopLoss: 178.0,
    takeProfits: [
      { price: 215.0, probability: 75, timeframe: "3-5 days" },
      { price: 235.0, probability: 55, timeframe: "1-2 weeks" },
      { price: 260.0, probability: 35, timeframe: "1 month" },
    ],
    riskRewardRatio: 2.8,
    riskScore: 34,
    volatilityLevel: "medium",
    expectedDrawdown: 8.7,
    probabilityOfSuccess: 79,
    timeHorizon: "medium",
    reasoning: [
      "Breaking above key resistance at $195 with strong volume",
      "RSI showing bullish divergence from oversold levels",
      "Institutional accumulation detected on-chain",
      "Positive catalyst: Upcoming network upgrade announcement",
    ],
    technicalIndicators: {
      rsi: 58,
      macd: "bullish",
      movingAverages: "above",
      volume: "high",
    },
    marketConditions: ["Bullish momentum", "Risk-on market", "High liquidity"],
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    expiresAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "sig-2",
    coinId: "ethereum",
    symbol: "ETH",
    name: "Ethereum",
    image: "https://assets.coingecko.com/coins/images/279/small/ethereum.png",
    signalType: "BUY",
    confidence: 78,
    currentPrice: 3842.5,
    entryPrice: 3800.0,
    stopLoss: 3550.0,
    takeProfits: [
      { price: 4100.0, probability: 70, timeframe: "1 week" },
      { price: 4500.0, probability: 50, timeframe: "2-3 weeks" },
    ],
    riskRewardRatio: 2.2,
    riskScore: 42,
    volatilityLevel: "medium",
    expectedDrawdown: 6.6,
    probabilityOfSuccess: 73,
    timeHorizon: "medium",
    reasoning: [
      "ETH/BTC ratio showing strength after prolonged weakness",
      "Layer 2 adoption metrics at all-time highs",
      "Gas fees at 3-month lows indicating healthy network",
      "Strong support at $3,600 level held multiple times",
    ],
    technicalIndicators: {
      rsi: 52,
      macd: "neutral",
      movingAverages: "crossing",
      volume: "normal",
    },
    marketConditions: ["Consolidation phase", "Building momentum"],
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "sig-3",
    coinId: "bitcoin",
    symbol: "BTC",
    name: "Bitcoin",
    image: "https://assets.coingecko.com/coins/images/1/small/bitcoin.png",
    signalType: "HOLD",
    confidence: 82,
    currentPrice: 97542.0,
    entryPrice: 97000.0,
    stopLoss: 92000.0,
    takeProfits: [
      { price: 105000.0, probability: 65, timeframe: "2 weeks" },
      { price: 115000.0, probability: 40, timeframe: "1 month" },
    ],
    riskRewardRatio: 1.6,
    riskScore: 48,
    volatilityLevel: "low",
    expectedDrawdown: 5.2,
    probabilityOfSuccess: 68,
    timeHorizon: "long",
    reasoning: [
      "Price consolidating below psychological $100K level",
      "ETF inflows remain strong but slowing",
      "Miners showing low selling pressure",
      "Waiting for clear breakout above resistance",
    ],
    technicalIndicators: {
      rsi: 62,
      macd: "neutral",
      movingAverages: "above",
      volume: "normal",
    },
    marketConditions: ["Range-bound", "Awaiting catalyst"],
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    expiresAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "sig-4",
    coinId: "ripple",
    symbol: "XRP",
    name: "XRP",
    image:
      "https://assets.coingecko.com/coins/images/44/small/xrp-symbol-white-128.png",
    signalType: "SELL",
    confidence: 72,
    currentPrice: 2.34,
    entryPrice: 2.4,
    stopLoss: 2.55,
    takeProfits: [
      { price: 2.15, probability: 70, timeframe: "3-5 days" },
      { price: 1.95, probability: 50, timeframe: "1-2 weeks" },
    ],
    riskRewardRatio: 1.8,
    riskScore: 57,
    volatilityLevel: "medium",
    expectedDrawdown: 6.3,
    probabilityOfSuccess: 62,
    timeHorizon: "short",
    reasoning: [
      "Failed to break above $2.50 resistance multiple times",
      "RSI showing bearish divergence at overbought levels",
      "Volume declining on each rally attempt",
      "Regulatory uncertainty increasing",
    ],
    technicalIndicators: {
      rsi: 68,
      macd: "bearish",
      movingAverages: "below",
      volume: "low",
    },
    marketConditions: ["Weakening momentum", "Distribution pattern"],
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    expiresAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "sig-5",
    coinId: "dogecoin",
    symbol: "DOGE",
    name: "Dogecoin",
    image: "https://assets.coingecko.com/coins/images/5/small/dogecoin.png",
    signalType: "STRONG_SELL",
    confidence: 68,
    currentPrice: 0.3842,
    entryPrice: 0.38,
    stopLoss: 0.42,
    takeProfits: [
      { price: 0.32, probability: 65, timeframe: "1 week" },
      { price: 0.28, probability: 45, timeframe: "2 weeks" },
    ],
    riskRewardRatio: 1.5,
    riskScore: 71,
    volatilityLevel: "high",
    expectedDrawdown: 10.5,
    probabilityOfSuccess: 51,
    timeHorizon: "short",
    reasoning: [
      "Parabolic move showing exhaustion signals",
      "Whale wallets distributing to retail",
      "Social sentiment peaking (contrarian indicator)",
      "High volatility with no fundamental support",
    ],
    technicalIndicators: {
      rsi: 78,
      macd: "bearish",
      movingAverages: "above",
      volume: "high",
    },
    marketConditions: ["Extreme greed", "Distribution phase", "High risk"],
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    expiresAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
];

export const mockWhaleTransactions: WhaleTransaction[] = [
  {
    id: "whale-1",
    coinId: "bitcoin",
    symbol: "BTC",
    type: "exchange_outflow",
    amount: 2500,
    valueUsd: 243855000,
    from: "Coinbase",
    to: "Unknown Wallet",
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    impact: "bullish",
    aiAnalysis:
      "Large withdrawal from exchange suggests accumulation by institution or whale. Historically bullish signal as coins move to cold storage.",
    exchangeFlowAnalysis: {
      classification: "strong_accumulation",
      netDirectionLabel: "Coinbase → Cold Storage",
      contextNote:
        "Massive supply removal — coins no longer available for immediate sale on this exchange",
    },
    accumulationPattern: {
      patternType: "accumulation",
      confidence: 88,
      description:
        "2,500 BTC withdrawn from Coinbase to private custody. Consistent with institutional cold-storage stacking or strategic long-term hold.",
    },
    marketImpactEstimate: {
      timeframe: "1-24h",
      priceEffect: "strong_bullish",
      magnitude: "high",
      note: "Consecutive large Coinbase outflows accelerating exchange BTC depletion. Historically precedes 5–10% price rallies.",
    },
  },
  {
    id: "whale-2",
    coinId: "ethereum",
    symbol: "ETH",
    type: "exchange_inflow",
    amount: 15000,
    valueUsd: 57637500,
    from: "Unknown Wallet",
    to: "Binance",
    timestamp: new Date(Date.now() - 45 * 60 * 1000),
    impact: "bearish",
    aiAnalysis:
      "Significant deposit to exchange. Monitor for potential selling pressure in next 24-48 hours.",
    exchangeFlowAnalysis: {
      classification: "distribution",
      netDirectionLabel: "Unknown Wallet → Binance",
      contextNote:
        "Coins entering exchange sell queue — distribution signal detected",
    },
    accumulationPattern: {
      patternType: "distribution",
      confidence: 71,
      description:
        "15,000 ETH moving from unknown private wallet to Binance. No prior pattern identified on this wallet — first large movement.",
    },
    marketImpactEstimate: {
      timeframe: "1-24h",
      priceEffect: "bearish",
      magnitude: "medium",
      note: "$57M potential ETH sell pressure on Binance. Watch for large limit-sell orders forming in the $3,800–$3,900 range.",
    },
  },
  {
    id: "whale-3",
    coinId: "solana",
    symbol: "SOL",
    type: "transfer",
    amount: 500000,
    valueUsd: 99225000,
    from: "FTX Estate",
    to: "Galaxy Digital",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    impact: "neutral",
    aiAnalysis:
      "FTX estate transfer to known market maker. Likely OTC deal, minimal immediate market impact expected.",
    exchangeFlowAnalysis: {
      classification: "neutral_flow",
      netDirectionLabel: "FTX Estate → Galaxy Digital (OTC)",
      contextNote:
        "Transfer between two known entities — confirmed OTC block settlement, not a market order",
    },
    accumulationPattern: {
      patternType: "otc_deal",
      confidence: 84,
      description:
        "500K SOL transferred from FTX Estate liquidation wallet to Galaxy Digital. Part of ongoing estate settlement — pre-arranged OTC at negotiated price.",
    },
    marketImpactEstimate: {
      timeframe: "1-7d",
      priceEffect: "neutral",
      magnitude: "low",
      note: "No immediate book impact. Galaxy may gradually deploy SOL as part of fund strategy over the coming days.",
    },
  },
  {
    id: "whale-4",
    coinId: "bitcoin",
    symbol: "BTC",
    type: "exchange_outflow",
    amount: 1800,
    valueUsd: 175575600,
    from: "Kraken",
    to: "Unknown Wallet",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    impact: "bullish",
    aiAnalysis:
      "Consecutive large outflows from exchanges continue. Supply squeeze narrative strengthening.",
    exchangeFlowAnalysis: {
      classification: "strong_accumulation",
      netDirectionLabel: "Kraken → Cold Storage",
      contextNote:
        "Second large BTC outflow in session — consecutive accumulation pattern forming across multiple exchanges",
    },
    accumulationPattern: {
      patternType: "accumulation",
      confidence: 91,
      description:
        "Back-to-back large Kraken BTC withdrawals (whale-1 + whale-4) signal coordinated institutional DCA accumulation across venues.",
    },
    marketImpactEstimate: {
      timeframe: "1-24h",
      priceEffect: "strong_bullish",
      magnitude: "high",
      note: "Multi-exchange outflow pattern tightening available BTC float. Supply squeeze probability elevated — historically bullish 5–10% in 24h.",
    },
  },
  {
    id: "whale-5",
    coinId: "dogecoin",
    symbol: "DOGE",
    type: "exchange_inflow",
    amount: 250000000,
    valueUsd: 96050000,
    from: "Robinhood",
    to: "Binance",
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    impact: "bearish",
    aiAnalysis:
      "Massive DOGE deposit. Likely selling from recent rally gains. High probability of dump incoming.",
    exchangeFlowAnalysis: {
      classification: "strong_distribution",
      netDirectionLabel: "Robinhood → Binance",
      contextNote:
        "Massive DOGE repositioned to exchange — high probability of imminent sell-off",
    },
    accumulationPattern: {
      patternType: "distribution",
      confidence: 85,
      description:
        "250M DOGE moved from Robinhood retail pool to Binance. Consistent with post-rally profit-taking at scale from retail aggregator.",
    },
    marketImpactEstimate: {
      timeframe: "immediate",
      priceEffect: "strong_bearish",
      magnitude: "high",
      note: "250M DOGE = $96M potential sell pressure. Significant enough to move price 3–8% if sold at market. High dump probability.",
    },
  },
];

export const mockPredictions: PricePrediction[] = [
  {
    coinId: "bitcoin",
    symbol: "BTC",
    currentPrice: 97542,
    predictions: [
      {
        timeframe: "1h",
        predictedPrice: 97800,
        confidence: 72,
        direction: "up",
        percentChange: 0.26,
      },
      {
        timeframe: "24h",
        predictedPrice: 99200,
        confidence: 68,
        direction: "up",
        percentChange: 1.7,
      },
      {
        timeframe: "7d",
        predictedPrice: 103500,
        confidence: 62,
        direction: "up",
        percentChange: 6.11,
      },
      {
        timeframe: "30d",
        predictedPrice: 115000,
        confidence: 55,
        direction: "up",
        percentChange: 17.9,
      },
    ],
    supportLevels: [95000, 92000, 88000],
    resistanceLevels: [100000, 105000, 110000],
    aiAnalysis:
      "Bitcoin showing strong accumulation pattern. ETF flows remain positive. Key breakout level at $100K. Risk of pullback to $92K if momentum fades.",
  },
  {
    coinId: "ethereum",
    symbol: "ETH",
    currentPrice: 3842.5,
    predictions: [
      {
        timeframe: "1h",
        predictedPrice: 3855,
        confidence: 70,
        direction: "up",
        percentChange: 0.33,
      },
      {
        timeframe: "24h",
        predictedPrice: 3920,
        confidence: 65,
        direction: "up",
        percentChange: 2.02,
      },
      {
        timeframe: "7d",
        predictedPrice: 4150,
        confidence: 60,
        direction: "up",
        percentChange: 8.0,
      },
      {
        timeframe: "30d",
        predictedPrice: 4800,
        confidence: 52,
        direction: "up",
        percentChange: 24.92,
      },
    ],
    supportLevels: [3600, 3400, 3200],
    resistanceLevels: [4000, 4200, 4500],
    aiAnalysis:
      "ETH consolidating after Dencun upgrade. L2 adoption accelerating. Watch for ETH/BTC ratio recovery as catalyst.",
  },
  {
    coinId: "solana",
    symbol: "SOL",
    currentPrice: 198.45,
    predictions: [
      {
        timeframe: "1h",
        predictedPrice: 201,
        confidence: 75,
        direction: "up",
        percentChange: 1.29,
      },
      {
        timeframe: "24h",
        predictedPrice: 212,
        confidence: 70,
        direction: "up",
        percentChange: 6.83,
      },
      {
        timeframe: "7d",
        predictedPrice: 245,
        confidence: 65,
        direction: "up",
        percentChange: 23.45,
      },
      {
        timeframe: "30d",
        predictedPrice: 300,
        confidence: 55,
        direction: "up",
        percentChange: 51.17,
      },
    ],
    supportLevels: [185, 170, 155],
    resistanceLevels: [210, 235, 260],
    aiAnalysis:
      "Solana showing strongest momentum among majors. DeFi TVL hitting new highs. Memecoin activity driving transaction volume.",
  },
  {
    coinId: "ripple",
    symbol: "XRP",
    currentPrice: 2.34,
    predictions: [
      {
        timeframe: "1h",
        predictedPrice: 2.32,
        confidence: 65,
        direction: "down",
        percentChange: -0.85,
      },
      {
        timeframe: "24h",
        predictedPrice: 2.25,
        confidence: 62,
        direction: "down",
        percentChange: -3.85,
      },
      {
        timeframe: "7d",
        predictedPrice: 2.1,
        confidence: 58,
        direction: "down",
        percentChange: -10.26,
      },
      {
        timeframe: "30d",
        predictedPrice: 2.5,
        confidence: 50,
        direction: "up",
        percentChange: 6.84,
      },
    ],
    supportLevels: [2.2, 2.0, 1.8],
    resistanceLevels: [2.5, 2.75, 3.0],
    aiAnalysis:
      "XRP facing distribution pressure after rally. Regulatory clarity still pending. Short-term bearish, long-term depends on legal outcomes.",
  },
];
