#!/usr/bin/env bash
# Run once ON the VPS (Ubuntu or Oracle/RHEL-like) as your deploy user (e.g. opc).
set -euo pipefail

BOT_DIR="${BOT_DIR:-$HOME/binance-bot}"
ENTRY="${ENTRY:-main.ts}"
BOT_NAME="${BOT_NAME:-binance-bot}"

log() {
  printf '[setup-server] %s\n' "$*"
}

have() {
  command -v "$1" >/dev/null 2>&1
}

die() {
  printf '%s\n' "$*" >&2
  exit 1
}

install_os_base() {
  if have apt-get; then
    sudo apt-get update -y
    sudo apt-get install -y curl ca-certificates gnupg
  elif have dnf; then
    sudo dnf install -y curl ca-certificates
  elif have yum; then
    sudo yum install -y curl ca-certificates
  else
    die "Unsupported package manager (need apt-get, dnf, or yum)"
  fi
}

install_firewall_hints() {
  log "Outbound HTTPS to Binance: host firewalls rarely block egress; rely on ACCEPT default."
  log "OCI/AWS: confirm security group / NSG egress allows TCP 443 (and 9443 if you use websocket APIs)."
  if have firewall-cmd && sudo firewall-cmd --state >/dev/null 2>&1; then
    sudo firewall-cmd --permanent --add-service=https || true
    sudo firewall-cmd --permanent --add-service=http || true
    sudo firewall-cmd --reload || true
    log "firewalld: allowed incoming http/https (for optional gateway). Outbound unchanged."
  elif have ufw; then
    sudo ufw default allow outgoing || true
    sudo ufw default deny incoming || true
    sudo ufw allow OpenSSH || true
    sudo ufw --force enable || true
    log "ufw: default outgoing allowed."
  fi
}

install_node_pm2() {
  if ! have npm; then
    if have apt-get; then
      sudo apt-get install -y nodejs npm || {
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        sudo apt-get install -y nodejs
      }
    elif have dnf; then
      sudo dnf install -y nodejs npm
    elif have yum; then
      sudo yum install -y nodejs npm
    fi
  fi
  have npm || die "npm not available after install attempts"
  if ! sudo npm list -g --depth=0 pm2 >/dev/null 2>&1; then
    sudo npm install -g pm2
  fi
  hash -r 2>/dev/null || true
  export PATH="/usr/local/bin:/usr/bin:$PATH"
}

install_deno() {
  export DENO_INSTALL="${DENO_INSTALL:-$HOME/.deno}"
  if ! [[ -x "$DENO_INSTALL/bin/deno" ]]; then
    curl -fsSL https://deno.land/install.sh | sh
  fi
  # shellcheck disable=SC2016
  grep -q 'DENO_INSTALL=' "$HOME/.bashrc" 2>/dev/null || echo "export DENO_INSTALL=\"\$HOME/.deno\"" >>"$HOME/.bashrc"
  # shellcheck disable=SC2016
  grep -q '$DENO_INSTALL/bin' "$HOME/.bashrc" 2>/dev/null || echo 'export PATH="$DENO_INSTALL/bin:$PATH"' >>"$HOME/.bashrc"
  export PATH="$DENO_INSTALL/bin:$PATH"
  deno --version
}

write_ecosystem() {
  mkdir -p "$BOT_DIR"
  DENO_BIN="$DENO_INSTALL/bin/deno"
  [[ -x "$DENO_BIN" ]] || die "Deno missing at $DENO_BIN"
  [[ -f "$BOT_DIR/$ENTRY" ]] || log "Warning: $BOT_DIR/$ENTRY not found yet; deploy code first, then pm2 restart $BOT_NAME"

  cat >"$BOT_DIR/ecosystem.config.cjs" <<EOF
/** Generated by setup-server.sh — edit ENTRY via redeploy or env before re-run */
module.exports = {
  apps: [
    {
      name: '${BOT_NAME}',
      cwd: '${BOT_DIR}',
      script: '${ENTRY}',
      interpreter: '${DENO_BIN}',
      interpreter_args: 'run --allow-net --allow-env --allow-read',
      instances: 1,
      autorestart: true,
      max_restarts: 100,
      min_uptime: '10s',
      exp_backoff_restart_delay: 2000,
    },
  ],
};
EOF
}

pm2_bootstrap() {
  export PATH="$DENO_INSTALL/bin:$PATH:/usr/local/bin:$PATH"
  have pm2 || die "pm2 not on PATH (try: hash -r; which pm2)"
  cd "$BOT_DIR"
  pm2 delete "$BOT_NAME" 2>/dev/null || true
  pm2 start ecosystem.config.cjs
  pm2 save
}

pm2_startup_systemd() {
  export PATH="$DENO_INSTALL/bin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:$PATH"
  PM2_HOME="${PM2_HOME:-$HOME/.pm2}"
  mkdir -p "$PM2_HOME"
  PM2_BIN="$(command -v pm2 || true)"
  [[ -n "$PM2_BIN" ]] || die "pm2 binary not found; re-login or export PATH=/usr/local/bin:\$PATH"
  if have systemctl && systemctl --version >/dev/null 2>&1; then
    sudo env HOME="$HOME" PM2_HOME="$PM2_HOME" PATH="$PATH" \
      "$PM2_BIN" startup systemd -u "$(id -un)" --hp "$HOME"
    pm2 save
  else
    log "No systemd detected; use pm2 resurrect or a custom service for boot persistence."
  fi
}

install_os_base
install_firewall_hints
install_deno
install_node_pm2
write_ecosystem
pm2_bootstrap
pm2_startup_systemd

log "Finished. Bot dir: $BOT_DIR | entry: $ENTRY"
log "Check: pm2 status"
log "Deploy updated code from Mac: ./scripts/deploy.sh then pm2 restart $BOT_NAME"
